$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: sklearn-env
version: 1
description: Environment with scikit-learn and pandas
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest

conda_file:
  conda_dependencies:
    channels:
      - conda-forge
      - defaults
    dependencies:
      - python=3.8
      - scikit-learn
      - pandas
      - pip
      - pip:
          - joblib
